#!/bin/bash
# enable service
sudo systemctl enable trek-tracker
# configure tracker (https://stackoverflow.com/a/3232082/19371130)
read -r -p "Do you wish to configure the tracker now? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
        sudo nano /etc/trek-tracker/trek-tracker.conf
        ;;
    *)
        echo Installation complete. Be sure to restart to enable serial port.
        ;;
esac
# restart
echo Reboot is required for finishing the installation and enabling serial port.
read -r -p "Do you wish to reboot now? [y/N] " response
case "$response" in
    [yY][eE][sS]|[yY]) 
        echo Rebooting now...
        sudo reboot now
        ;;
    *)
        echo Installation complete. Be sure to reboot for serial port to be correctly enabled.
        sudo systemctl start trek-tracker
        ;;
esac
