#!/bin/bash
# stop service
sudo systemctl stop trek-tracker
# delete trek directory if exists
DIR="/usr/bin/trek-tracker/"
if test -e $DIR; then
    sudo rm -r $DIR
fi
# uninstall python dependencies
sudo pip3 uninstall -y pyserial pynmea2 python-socketio==4.6.1 configparser